import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Electrolize } from "next/font/google";
import "./globals.css";

const inter = Electrolize({ weight: ["400"], display:'swap', subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
